export const INVALID_JSON = 'ERR_LWRF_INVALID_JSON';
export const UNSUCCESSFUL_HTTP_RESPONSE = 'ERR_LWRF_UNSUCCESSFUL_HTTP_RESPONSE';
export const UNABLE_TO_SEND_REQUEST = 'ERR_LWRF_UNABLE_TO_SEND_REQUEST';
export const UNSUCCESSFUL_REQUEST = 'ERR_LWRF_UNSUCCESSFUL_REQUEST';
export const TIMED_OUT_WAITING_FOR_RESPONSE = 'ERR_LWRF_TIMED_OUT_WAITING_FOR_RESPONSE';
export const WEBSOCKET_CLOSED_WHILE_WAITING_FOR_RESPONSE = 'WEBSOCKET_CLOSED_WHILE_WAITING_FOR_RESPONSE';
export const CANNOT_RECONNECT_IN_CURRENT_STATE = 'ERR_LWRF_CANNOT_RECONNECT_IN_CURRENT_STATE';
export const CANNOT_SEND_REQUEST_IN_CURRENT_STATE = 'ERR_LWRF_CANNOT_SEND_REQUEST_IN_CURRENT_STATE';
export const CANNOT_CONNECT_TO_WEBSOCKET = 'ERR_LWRF_CANNOT_CONNECT_TO_WEBSOCKET';

export default class LightwaveRfError extends Error {
  constructor(code, description, error) {
    super(description || code);

    this.code = code;
    this.error = error;
  }
}
